### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by sumukund** [astaka-pe/Dual-DMP#2]
Hi, I've run into this error: 
```
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 64, in main
    pos = posnet(dataset)
  File "/opt/conda/envs/ddmp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jovyan/Dual-DMP/util/networks.py", line 51, in forward
    dx = self.l_relu(self.bn1(self.conv1(z1, edge_index)))
  File "/opt/conda/envs/ddmp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/ddmp/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/opt/conda/envs/ddmp/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

I was wondering if anyone else had a similar issue and if so, what they did to resolve it. Thank you

**Comment by sumukund** [comment]
Resolved. My environment didn't allow me to use CUDA 10.2 so I updated to CUDA 11.0 with torch 1.7.0 
Leaving this here in case anyone faces the same problem!
`pip install torch==1.7.0+cu110 torchvision==0.8.0+cu110 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`
