### ISSUE TITLE
OOM error when running on own meshes?

### ISSUE THREAD

**Issue by sumukund** [astaka-pe/Dual-DMP#3]
Hi, I'm running into a Killed error while training on my own meshes.
For reference, I'm using an A100 80GB nvidia GPU and 64 GB of ram. 
My meshes are roughly 50 mb or more, in obj format. 
Any ideas why this would be happening? would this code be able to work with a batched dataset loader?

**Comment by sumukund** [comment]
```
[5433965.014859] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[5433965.015221] [100950]     0 100950      651      164       5        0           985 dash
[5433965.015226] [101270]     0 101270  4311525    84517     308        0           985 jupyter-lab
[5433965.015227] [102268]     0 102268     2421     1550       9        0           985 bash
[5433965.015229] [102691]     0 102691     2421     1560       9        0           985 bash
[5433965.015230] [103089]     0 103089     1495      505       6        0           985 bash
[5433965.015232] [103108]     0 103108   154372     2737      73        0           985 node
[5433965.015233] [103190]     0 103190     1411      435       7        0           985 bash
[5433965.015235] [103245]     0 103245   234110    10869     257        0           985 node
[5433965.015236] [103415]     0 103415   231790     7445     134        0           985 node
[5433965.015249] [ 3972]     0  3972     1428       59       7        0           985 tar
[5433965.015254] [22302]     0 22302     1431       94       6        0           985 bash
[5433965.015255] [22477]     0 22477     1495      138       7        0           985 bash
[5433965.015257] [22496]     0 22496   154372     2442      71        0           985 node
[5433965.015258] [22840]     0 22840   170801     4009      70        0           985 node
[5433965.015260] [22902]     0 22902   208566     3501      89        0           985 node
[5433965.015261] [22934]     0 22934   170535     3611      71        0           985 node
[5433965.015263] [22957]     0 22957   238005    12583     283        0           985 node
[5433965.015265] [23019]     0 23019     2421     1130       8        0           985 bash
[5433965.015266] [23030]     0 23030     2421     1116      10        0           985 bash
[5433965.015286] [95403]     0 95403 1254627805 16657313   33152        0           985 python
[5433965.015288] [95876]     0 95876     2421     1127      10        0           985 bash
[5433965.015291] [97891]     0 97891     1907       72       7        0           985 git
[5433965.015293] Memory cgroup out of memory: Kill process 97725 (python) score 1979 or sacrifice child
[5433965.025497] Killed process 95403 (python), UID 0, total-vm:5018511220kB, anon-rss:66558476kB, file-rss:70776kB, shmem-rss:0kB
```

**Comment by astaka-pe** [comment]
Hi @sumukund,

> For reference, I'm using an A100 80GB nvidia GPU and 64 GB of ram.
My meshes are roughly 50 mb or more, in obj format.

as noted in the [supplemental document](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136630358-supp.pdf), we used the meshes with less than 50,000 vertices and 100,000 faces (4 mb), so the size of your mesh may be too large.
If you want to process without any mesh simplification, you should separate the original mesh into the small patches.

> would this code be able to work with a batched dataset loader?

Currently, it doesn't work. GCNConv doesn't seem to support batch inputs of graph.

**Comment by sumukund** [comment]
@astaka-pe One more question- does this only work on manifold meshes? Can it work on meshes that are more noisy and may have unconnected faces and vertices- I keep getting the following error 
`Traceback (most recent call last):
  File "preprocess/preprocess.py", line 79, in <module>
    main()
  File "preprocess/preprocess.py", line 62, in main
    n_mesh = Mesh(n_file)
  File "/root/dualdmpfork/util/mesh.py", line 21, in __init__
    self.build_gemm() #self.edges, self.ve
  File "/root/dualdmpfork/util/mesh.py", line 84, in build_gemm
    edge_nb[edge_key][nb_count[edge_key]] = edge2key[faces_edges[(idx + 1) % 3]]
IndexError: list assignment index out of range
(ddmp) root@dualeight-0:~/dualdmpfork# `

**Comment by astaka-pe** [comment]
@sumukund Unfortunately, it cannot be used for non-manifold meshes. Please use [MeshFix](https://github.com/MarcoAttene/MeshFix-V2.1) or [pymeshfix](https://github.com/pyvista/pymeshfix) beforehand to create a single watertight triangle mesh.
