### ISSUE TITLE
Not able to run on different obj than examples

### ISSUE THREAD

**Issue by ujjwal-kumar19** [astaka-pe/Dual-DMP#5]
input       : datasets/spec2
pos_lr      : 0.01
norm_lr     : 0.01
iter        : 50
k1          : 3
k2          : 0
k3          : 3
k4          : 4
k5          : 2
grad_crip   : 0.8
bnfloop     : 5
gpu         : 0
Traceback (most recent call last):
  File "main4real.py", line 89, in <module>
    main()
  File "main4real.py", line 37, in main
    mesh_dic, dataset = Datamaker.create_dataset(args.input)
  File "/content/drive/MyDrive/Colab Notebooks/mesh_denoise/Dual-DMP/util/datamaker.py", line 37, in create_dataset
    n_mesh = Mesh(n_file)
  File "/content/drive/MyDrive/Colab Notebooks/mesh_denoise/Dual-DMP/util/mesh.py", line 15, in __init__
    self.build_gemm() #self.edges, self.ve
  File "/content/drive/MyDrive/Colab Notebooks/mesh_denoise/Dual-DMP/util/mesh.py", line 75, in build_gemm
    edge_nb[edge_key][nb_count[edge_key]] = edge2key[faces_edges[(idx + 1) % 3]]
IndexError: list assignment index out of range

**Comment by astaka-pe** [comment]
@ujjwalinvent 
Unfortunately, it cannot be used for non-manifold meshes. Please use [MeshFix](https://github.com/MarcoAttene/MeshFix-V2.1) or [pymeshfix](https://github.com/pyvista/pymeshfix) beforehand to create a single watertight triangle mesh.
https://github.com/astaka-pe/Dual-DMP/issues/3#issuecomment-1379742504
