### ISSUE TITLE
Errors. Seems like torch-geometric?

### ISSUE THREAD

**Issue by CrescentRosexx** [astaka-pe/Dual-DMP#6]
I was running windows10 and torch_sparse was only available in 0.6.8 and 0.6.9 when I was using environment.yml. I didn't know if this had anything to do with it. Then when I was using torch_geometric 1.7.1, Running any command in readme results in the following error:

```
Traceback (most recent call last):
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\main4real.py", line 89, in <module>
    main()
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\main4real.py", line 62, in main
    norm = normnet(dataset)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\util\networks.py", line 112, in forward
    dx = self.l_relu(self.bn1(self.conv1(z2, edge_index)))
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 160, in forward
    edge_index, edge_weight = gcn_norm(  # yapf: disable
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 62, in gcn_norm
    deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_scatter\scatter.py", line 29, in scatter_add
    return scatter_sum(src, index, dim, out, dim_size)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_scatter\scatter.py", line 21, in scatter_sum
    return out.scatter_add_(dim, index, src)
IndexError: scatter_(): Expected dtype int64 for index.
```

And the following error was generated when I changed torch_geometirc version to 2.2.0:
```
Traceback (most recent call last):
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\main4real.py", line 89, in <module>
    main()
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\main4real.py", line 62, in main
    norm = normnet(dataset)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Ddrive\Papers\Code\3Dual-DMP-main\util\networks.py", line 112, in forward
    dx = self.l_relu(self.bn1(self.conv1(z2, edge_index)))
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 176, in forward
    edge_index, edge_weight = gcn_norm(  # yapf: disable
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 61, in gcn_norm
    edge_index, tmp_edge_weight = add_remaining_self_loops(
  File "C:\Ddrive\Programs\Anaconda3\envs\torch191\lib\site-packages\torch_geometric\utils\loop.py", line 298, in add_remaining_self_loops
    loop_attr[edge_index[0][inv_mask]] = edge_attr[inv_mask]
IndexError: tensors used as indices must be long, byte or bool tensors
```

**Comment by CrescentRosexx** [comment]
I've done this successfully by using torch_geometric 1.7.1 and then casting edge_index from the forward function in NormNet
```
edge_index = edge_index.to(torch.int64)
```
