### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by ltrbless** [astaka-pe/Dual-DMP#9]
This error appears to be a library version issue, however I am using miniconda for administration in a Linux environment. I ran "conda env create -f environment.yml" and "conda activate ddmp" to make sure the ddmp environment was in. Then I executed "python main.py -i . /data/fandisk --k1 3 --k2 0 --k3 3 --k4 4 --k5 2 --bnfloop 5", the following error occurred:

Traceback (most recent call last):
  File "./main.py", line 9, in <module>
    import util.datamaker as Datamaker
  File "/home/ltr/Nworkspace/DeepLearning/Dual-DMP/util/datamaker.py", line 5, in <module>
    from torch_geometric.data import Data
  File "/home/ltr/miniconda3/envs/ddmp/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/ltr/miniconda3/envs/ddmp/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/ltr/miniconda3/envs/ddmp/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/ltr/miniconda3/envs/ddmp/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

Hope you can provide some help, thanks!

**Comment by ltrbless** [comment]
I have solved this problem. I recreated a python 3.7 environment with conda and executed python main.py. In the process, I installed whatever libraries were missing according to the error and it finally worked. Excuse me, thanks!
